apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventsourcedservices.statefulserverless.lightbend.com
spec:
  group: statefulserverless.lightbend.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: eventsourcedservices
    singular: eventsourcedservice
    kind: EventSourcedService
    shortNames:
    - ess
  subresources:
    status: {}
