apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stateful-serverless-operator-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - statefulserverless.lightbend.com
  resources:
  - eventsourcedjournals
  - eventsourcedservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - statefulserverless.lightbend.com
  resources:
  - eventsourcedjournals/status
  - eventsourcedservices/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
