apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: stateful-serverless-operator
subjects:
- kind: ServiceAccount
  name: stateful-serverless-operator
  # Update to the account the operator is deployed to
  namespace: default
roleRef:
  kind: Role
  name: stateful-serverless-operator-role
  apiGroup: rbac.authorization.k8s.io