apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: journals.cloudstate.io
spec:
  group: cloudstate.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: journals
    singular: journal
    kind: Journal
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Type
    type: string
    description: The type of event sourced Journal
    JSONPath: .spec.type
  - name: Service
    type: string
    description: The service that serves this journal
    JSONPath: .spec.config.service
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:

            type:
              type: string
              enum:
              - Cassandra

            deployment:
              type: string
              enum:
              - Unmanaged

            config:
              type: object

          required:
          - type
          - deployment

