# Deployment spec for our shopping cart event sourced function
apiVersion: statefulserverless.lightbend.com/v1alpha1
kind: EventSourcedService
metadata:
  name: shopping-cart
spec:

  # How many replicas of the function should be deployed
  # Eventually, this should be replaced with min/max constraints, and be dynamically scaled.
  replicas: 3

  # Journal configuration
  journal:

    # Name of a deployed EventSourcedJournal to use, must match the name configured above.
    # A namespace might also be specified.
    name: cassandra

    # Journal specific configuration
    config:

      # Since the journal is a Cassandra journal, we need to specify the keyspace to use.
      keyspace: shoppingcart

  template:
    spec:
      # Like Knative Serving, this is the containers configuration
      containers:
      - image: lightbend-docker-registry.bintray.io/octo/js-shopping-cart:0.3

        # This enables some interesting logging to see what messages are being passed between
        # the sidecar and the user function.
        env:
        - name: DEBUG
          value: stateserve-event-sourcing
