apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cloudstate-operator-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - cloudstate.io
  resources:
  - eventsourcedjournals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudstate.io
  resources:
  - eventsourcedjournals/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
