apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventsourcedjournals.statefulserverless.lightbend.com
spec:
  group: statefulserverless.lightbend.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: eventsourcedjournals
    singular: eventsourcedjournal
    kind: EventSourcedJournal
    shortNames:
    - esj
