apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventsourcedserviceconfigurations.statefulserverless.lightbend.com
spec:
  group: statefulserverless.lightbend.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: eventsourcedserviceconfigurations
    singular: eventsourcedserviceconfiguration
    kind: EventSourcedServiceConfiguration
    shortNames:
    - essc
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Journal
    type: string
    description: The journal being used
    JSONPath: .spec.journal.name
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Error
    type: string
    JSONPath: .status.reason
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:

            replicas:
              type: integer
              minimum: 0

            journal:
              type: object
              properties:
                name:
                  type: string
                config:
                  type: object
              required:
              - name

            template:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    containers:
                      type: array
                      items:
                        type: object
                        properties:
                          image:
                            type: string
                          # todo, other supported container properties
                        required:
                        - image
                  required:
                  - containers

          required:
          - replicas
          - journal
          - template

        status:
          type: object
          properties:
            appliedSpecHash:
              type: string
            journalConfigHash:
              type: string
            appliedJournalConfigHash:
              type: string
            reason:
              type: string

